[2023-12-26T09:30:43.959+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: custom_operators_legacy.load_stations_from_s3_to_redshift scheduled__2018-04-01T00:00:00+00:00 [queued]>
[2023-12-26T09:30:43.973+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: custom_operators_legacy.load_stations_from_s3_to_redshift scheduled__2018-04-01T00:00:00+00:00 [queued]>
[2023-12-26T09:30:43.974+0000] {taskinstance.py:2171} INFO - Starting attempt 1 of 1
[2023-12-26T09:30:43.992+0000] {taskinstance.py:2192} INFO - Executing <Task(S3ToRedshiftOperator): load_stations_from_s3_to_redshift> on 2018-04-01 00:00:00+00:00
[2023-12-26T09:30:44.002+0000] {standard_task_runner.py:60} INFO - Started process 15333 to run task
[2023-12-26T09:30:44.009+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'custom_operators_legacy', 'load_stations_from_s3_to_redshift', 'scheduled__2018-04-01T00:00:00+00:00', '--job-id', '35', '--raw', '--subdir', 'DAGS_FOLDER/production/production.py', '--cfg-path', '/tmp/tmpq0pc3z5o']
[2023-12-26T09:30:44.011+0000] {standard_task_runner.py:88} INFO - Job 35: Subtask load_stations_from_s3_to_redshift
[2023-12-26T09:30:44.082+0000] {task_command.py:423} INFO - Running <TaskInstance: custom_operators_legacy.load_stations_from_s3_to_redshift scheduled__2018-04-01T00:00:00+00:00 [running]> on host d3aa51350085
[2023-12-26T09:30:44.193+0000] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='custom_operators_legacy' AIRFLOW_CTX_TASK_ID='load_stations_from_s3_to_redshift' AIRFLOW_CTX_EXECUTION_DATE='2018-04-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2018-04-01T00:00:00+00:00'
[2023-12-26T09:30:44.205+0000] {s3_to_redshift.py:44} INFO - Clearing data from destination Redshift table
[2023-12-26T09:30:44.213+0000] {base.py:83} INFO - Using connection ID 'redshift' for task execution.
[2023-12-26T09:30:44.788+0000] {sql.py:432} INFO - Running statement: DELETE FROM stations, parameters: None
[2023-12-26T09:30:45.102+0000] {sql.py:441} INFO - Rows affected: 0
[2023-12-26T09:30:45.599+0000] {s3_to_redshift.py:47} INFO - Copying data from S3 to Redshift
[2023-12-26T09:30:45.600+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/utils/context.py:207: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2023-12-26T09:30:45.601+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/utils/context.py:207: AirflowContextDeprecationWarning: Accessing 'next_ds' from the template is deprecated and will be removed in a future version. Please use '{{ data_interval_end | ds }}' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2023-12-26T09:30:45.601+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/utils/context.py:207: AirflowContextDeprecationWarning: Accessing 'next_ds_nodash' from the template is deprecated and will be removed in a future version. Please use '{{ data_interval_end | ds_nodash }}' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2023-12-26T09:30:45.601+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/utils/context.py:207: AirflowContextDeprecationWarning: Accessing 'next_execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_end' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2023-12-26T09:30:45.601+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/utils/context.py:207: AirflowContextDeprecationWarning: Accessing 'prev_ds' from the template is deprecated and will be removed in a future version.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2023-12-26T09:30:45.601+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/utils/context.py:207: AirflowContextDeprecationWarning: Accessing 'prev_ds_nodash' from the template is deprecated and will be removed in a future version.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2023-12-26T09:30:45.602+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/utils/context.py:207: AirflowContextDeprecationWarning: Accessing 'prev_execution_date' from the template is deprecated and will be removed in a future version.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2023-12-26T09:30:45.602+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/utils/context.py:207: AirflowContextDeprecationWarning: Accessing 'prev_execution_date_success' from the template is deprecated and will be removed in a future version. Please use 'prev_data_interval_start_success' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2023-12-26T09:30:45.602+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/utils/context.py:207: AirflowContextDeprecationWarning: Accessing 'tomorrow_ds' from the template is deprecated and will be removed in a future version.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2023-12-26T09:30:45.602+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/utils/context.py:207: AirflowContextDeprecationWarning: Accessing 'tomorrow_ds_nodash' from the template is deprecated and will be removed in a future version.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2023-12-26T09:30:45.602+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/utils/context.py:207: AirflowContextDeprecationWarning: Accessing 'yesterday_ds' from the template is deprecated and will be removed in a future version.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2023-12-26T09:30:45.603+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/utils/context.py:207: AirflowContextDeprecationWarning: Accessing 'yesterday_ds_nodash' from the template is deprecated and will be removed in a future version.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2023-12-26T09:30:45.609+0000] {base.py:83} INFO - Using connection ID 'redshift' for task execution.
[2023-12-26T09:30:46.115+0000] {sql.py:432} INFO - Running statement: 
        COPY stations
        FROM 's3://gitongabretton/data-pipelines/divvy/unpartitioned/divvy_stations_2017.csv'
        ACCESS_KEY_ID 'AKIATZS7MBBSL3CADLWH'
        SECRET_ACCESS_KEY '***'
        IGNOREHEADER 1
        DELIMITER ','
    , parameters: None
[2023-12-26T10:13:06.303+0000] {taskinstance.py:2699} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/opt/airflow/plugins/custom_operators/s3_to_redshift.py", line 58, in execute
    redshift.run(formatted_sql)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/hooks/sql.py", line 392, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/hooks/sql.py", line 437, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.InternalError_: S3CurlException: Failed to connect to s3.us-east-1.amazonaws.com port 443: Connection timed out, CurlError 28, multiCurlError 0, CanRetry 1, UserError 0
DETAIL:  
  -----------------------------------------------
  error:  S3CurlException: Failed to connect to s3.us-east-1.amazonaws.com port 443: Connection timed out, CurlError 28, multiCurlError 0, CanRetry 1, UserError 0
  code:      9002
  context:   Listing bucket=gitongabretton prefix=data-pipelines/divvy/unpartitioned/divvy_stations_2017.csv
  query:     412283[child_sequence:1]
  location:  s3_utility.cpp:702
  process:   padbmaster [pid=1073930419]
  -----------------------------------------------


[2023-12-26T10:13:06.314+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=custom_operators_legacy, task_id=load_stations_from_s3_to_redshift, execution_date=20180401T000000, start_date=20231226T093043, end_date=20231226T101306
[2023-12-26T10:13:06.329+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 35 for task load_stations_from_s3_to_redshift (S3CurlException: Failed to connect to s3.us-east-1.amazonaws.com port 443: Connection timed out, CurlError 28, multiCurlError 0, CanRetry 1, UserError 0
DETAIL:  
  -----------------------------------------------
  error:  S3CurlException: Failed to connect to s3.us-east-1.amazonaws.com port 443: Connection timed out, CurlError 28, multiCurlError 0, CanRetry 1, UserError 0
  code:      9002
  context:   Listing bucket=gitongabretton prefix=data-pipelines/divvy/unpartitioned/divvy_stations_2017.csv
  query:     412283[child_sequence:1]
  location:  s3_utility.cpp:702
  process:   padbmaster [pid=1073930419]
  -----------------------------------------------

; 15333)
[2023-12-26T10:13:06.367+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2023-12-26T10:13:06.391+0000] {taskinstance.py:3281} INFO - 0 downstream tasks scheduled from follow-on schedule check
